#!/bin/bash

# Draw With Friends - Device Logging Setup
# Run this script to get instructions for logging both devices

echo "🎯 Draw With Friends - Device Logging Setup"
echo "=============================================="
echo ""

echo "Step 1: Find your device names"
echo "-------------------------------"
echo "Run this command to see all connected devices:"
echo ""
echo "    xcrun xctrace list devices"
echo ""
read -p "Press Enter after you've noted your device names..."

echo ""
echo "Step 2: Start logging"
echo "---------------------"
echo ""
echo "Open TWO separate Terminal windows and run these commands:"
echo ""
echo "📱 TERMINAL 1 - iPhone:"
echo "--------------------"
echo "log stream --device --predicate 'processImagePath CONTAINS \"Draw With Friends\"' --style compact"
echo ""
echo ""
echo "📱 TERMINAL 2 - iPad:"
echo "--------------------"
echo "log stream --device --predicate 'processImagePath CONTAINS \"Draw With Friends\"' --style compact"
echo ""
echo ""
echo "💡 TIP: If you have multiple devices, add --device-name to specify:"
echo "   log stream --device-name=\"Jamie's iPhone\" --predicate 'processImagePath CONTAINS \"Draw With Friends\"' --style compact"
echo ""
echo "Step 3: Test the app"
echo "--------------------"
echo "1. Launch Draw With Friends on BOTH devices"
echo "2. Join the same room"
echo "3. Draw on both devices"
echo "4. Watch the logs in both Terminal windows"
echo ""
echo "Step 4: Save logs (when done)"
echo "------------------------------"
echo "In each Terminal window:"
echo "1. Press Ctrl+C to stop logging"
echo "2. Select all text (Cmd+A)"
echo "3. Copy (Cmd+C)"
echo "4. Paste into a text file"
echo ""
echo "=============================================="
echo "✅ Ready to start logging!"
echo ""


